import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>
      </main>

      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque error ullam qui impedit consequuntur a expedita quos dolorem alias, similique voluptas, nesciunt, aut quo provident? Voluptate consequatur ipsum fugiat labore.</p>

    </>
  )
}

export default Home
